// <auto-generated />
using System;
using EcoPulseBackend.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoPulseBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260213085827_AddUpdatedAtToFlow")]
    partial class AddUpdatedAtToFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoPulseBackend.Models.City.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Polygon>("Polygon")
                        .IsRequired()
                        .HasColumnType("geometry(Polygon, 4326)");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.Enterprise.Enterprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Polygon>("SanitaryArea")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Enterprises");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.PollutantInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<float?>("DailyAverageConcentration")
                        .HasColumnType("real");

                    b.Property<float?>("Mass")
                        .HasColumnType("real");

                    b.Property<float?>("MaxPermissibleConcentration")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Pollutant")
                        .HasColumnType("integer");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float?>("SpecificEmission")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PollutantInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 2,
                            Mass = 15.72f,
                            MaxPermissibleConcentration = 0.5f,
                            Name = "Твердые частицы",
                            Pollutant = 2,
                            ShortName = "PM2.5"
                        },
                        new
                        {
                            Id = 2,
                            Code = 337,
                            DailyAverageConcentration = 3f,
                            MaxPermissibleConcentration = 5f,
                            Name = "Углерода оксид (углерод окись; углерод моноокись; угарный газ)",
                            Pollutant = 337,
                            ShortName = "CO",
                            SpecificEmission = 7.5f
                        },
                        new
                        {
                            Id = 3,
                            Code = 2704,
                            DailyAverageConcentration = 1.5f,
                            MaxPermissibleConcentration = 5f,
                            Name = "Бензин (нефтяной, малосернистый) /в пересчете на углерод/",
                            Pollutant = 2704,
                            ShortName = "CH",
                            SpecificEmission = 1f
                        },
                        new
                        {
                            Id = 4,
                            Code = 301,
                            DailyAverageConcentration = 0.04f,
                            Mass = 0.2695f,
                            MaxPermissibleConcentration = 0.2f,
                            Name = "Азота диоксид (двуокись азота; пероксид азота)",
                            Pollutant = 301,
                            ShortName = "NO2",
                            SpecificEmission = 0.112f
                        },
                        new
                        {
                            Id = 5,
                            Code = 304,
                            DailyAverageConcentration = 0.06f,
                            Mass = 0.0444f,
                            MaxPermissibleConcentration = 0.4f,
                            Name = "Азота оксид (азот (II) оксид; азот монооксид)",
                            Pollutant = 304,
                            ShortName = "NO",
                            SpecificEmission = 0.0182f
                        },
                        new
                        {
                            Id = 6,
                            Code = 330,
                            DailyAverageConcentration = 0.05f,
                            Mass = 1.0528f,
                            MaxPermissibleConcentration = 0.5f,
                            Name = "Серы диоксид",
                            Pollutant = 330,
                            ShortName = "SO2",
                            SpecificEmission = 0.036f
                        },
                        new
                        {
                            Id = 7,
                            Code = 2754,
                            MaxPermissibleConcentration = 1f,
                            Name = "Углеводороды предельные C12 - C19 (растворители РПК-240, РПК-280)",
                            Pollutant = 2754,
                            ShortName = "углеводороды",
                            SpecificEmission = 99.72f
                        },
                        new
                        {
                            Id = 8,
                            Code = 333,
                            MaxPermissibleConcentration = 0.008f,
                            Name = "Сероводород (дигидросульфид; водород сернистый; гидросульфид)",
                            Pollutant = 333,
                            ShortName = "дигидросульфид",
                            SpecificEmission = 0.28f
                        },
                        new
                        {
                            Id = 9,
                            Code = 123,
                            DailyAverageConcentration = 0.04f,
                            Name = "диЖелезо триоксид (железа оксид; железо сесквиоксид) /в пересчете на железо/",
                            Pollutant = 123,
                            ShortName = "Fe203"
                        },
                        new
                        {
                            Id = 10,
                            Code = 143,
                            DailyAverageConcentration = 0.001f,
                            MaxPermissibleConcentration = 0.01f,
                            Name = "Марганец и его соединения /в пересчете на марганец (IV) оксид/",
                            Pollutant = 143,
                            ShortName = "MnO2"
                        },
                        new
                        {
                            Id = 11,
                            Code = 342,
                            DailyAverageConcentration = 0.005f,
                            MaxPermissibleConcentration = 0.02f,
                            Name = "Фториды газообразные /в пересчете на фтор/: гидрофторид (водород фторид, фторводород); кремний тетрафторид",
                            Pollutant = 342,
                            ShortName = "FluorideGases"
                        },
                        new
                        {
                            Id = 12,
                            Code = 380,
                            Mass = 4.9f,
                            MaxPermissibleConcentration = 5f,
                            Name = "Углерод диоксид",
                            Pollutant = 380,
                            ShortName = "CO2"
                        },
                        new
                        {
                            Id = 13,
                            Code = 2,
                            Mass = 15.72f,
                            MaxPermissibleConcentration = 0.5f,
                            Name = "Твердые частицы",
                            Pollutant = 2,
                            ShortName = "SP"
                        },
                        new
                        {
                            Id = 14,
                            Code = 328,
                            Name = "Сажа",
                            Pollutant = 328,
                            ShortName = "Soot"
                        },
                        new
                        {
                            Id = 15,
                            Code = 184,
                            DailyAverageConcentration = 0.0003f,
                            MaxPermissibleConcentration = 0.001f,
                            Name = "Соединения свинца",
                            Pollutant = 184,
                            ShortName = "LeadCompounds"
                        },
                        new
                        {
                            Id = 16,
                            Code = 1325,
                            DailyAverageConcentration = 0.003f,
                            MaxPermissibleConcentration = 0.035f,
                            Name = "Формальдегид",
                            Pollutant = 1325,
                            ShortName = "CH2O"
                        },
                        new
                        {
                            Id = 17,
                            Code = 703,
                            Name = "Бенз(а)пирен",
                            Pollutant = 703,
                            ShortName = "C20H12"
                        },
                        new
                        {
                            Id = 18,
                            Code = 3749,
                            Name = "Пыль каменного угля",
                            Pollutant = 3749,
                            ShortName = "CoalDust"
                        });
                });

            modelBuilder.Entity("EcoPulseBackend.Models.SingleEmissionSource.SingleEmissionSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("AvgExitSpeed")
                        .HasColumnType("real");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<float>("DiameterSource")
                        .HasColumnType("real");

                    b.Property<float>("EjectedTemp")
                        .HasColumnType("real");

                    b.Property<int?>("EnterpriseId")
                        .HasColumnType("integer");

                    b.Property<float>("HeightSource")
                        .HasColumnType("real");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<int>("SedimentationRateRatio")
                        .HasColumnType("integer");

                    b.Property<int>("TempStratificationRatio")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("EnterpriseId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.ToTable("SingleEmissionSources");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.TrafficLightQueue.VehicleGroupQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TrafficLightQueueEmissionSourceId")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.Property<int>("VehiclesCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrafficLightQueueEmissionSourceId");

                    b.ToTable("VehicleGroupQueues");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.TrafficLightQueueEmissionSource.TrafficLightQueueEmissionSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<int>("TrafficLightCycles")
                        .HasColumnType("integer");

                    b.Property<float>("TrafficLightStopTime")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.ToTable("TrafficLightQueueEmissionSources");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.VaporConcentration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("AutumnWinterVaporConcentration")
                        .HasColumnType("real");

                    b.Property<int>("ClimateZone")
                        .HasColumnType("integer");

                    b.Property<float>("MaxVaporConcentration")
                        .HasColumnType("real");

                    b.Property<int>("OilProduct")
                        .HasColumnType("integer");

                    b.Property<int>("ReservoirType")
                        .HasColumnType("integer");

                    b.Property<float>("SpringSummerVaporConcentration")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("VaporConcentrations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutumnWinterVaporConcentration = 205f,
                            ClimateZone = 1,
                            MaxVaporConcentration = 464f,
                            OilProduct = 1,
                            ReservoirType = 1,
                            SpringSummerVaporConcentration = 248f
                        },
                        new
                        {
                            Id = 2,
                            AutumnWinterVaporConcentration = 0.79f,
                            ClimateZone = 1,
                            MaxVaporConcentration = 1.49f,
                            OilProduct = 2,
                            ReservoirType = 1,
                            SpringSummerVaporConcentration = 1.06f
                        },
                        new
                        {
                            Id = 3,
                            AutumnWinterVaporConcentration = 0.1f,
                            ClimateZone = 1,
                            MaxVaporConcentration = 0.16f,
                            OilProduct = 3,
                            ReservoirType = 1,
                            SpringSummerVaporConcentration = 0.1f
                        },
                        new
                        {
                            Id = 4,
                            AutumnWinterVaporConcentration = 250f,
                            ClimateZone = 2,
                            MaxVaporConcentration = 580f,
                            OilProduct = 1,
                            ReservoirType = 1,
                            SpringSummerVaporConcentration = 310f
                        },
                        new
                        {
                            Id = 5,
                            AutumnWinterVaporConcentration = 0.96f,
                            ClimateZone = 2,
                            MaxVaporConcentration = 1.86f,
                            OilProduct = 2,
                            ReservoirType = 1,
                            SpringSummerVaporConcentration = 1.32f
                        },
                        new
                        {
                            Id = 6,
                            AutumnWinterVaporConcentration = 0.12f,
                            ClimateZone = 2,
                            MaxVaporConcentration = 0.2f,
                            OilProduct = 3,
                            ReservoirType = 1,
                            SpringSummerVaporConcentration = 0.12f
                        },
                        new
                        {
                            Id = 7,
                            AutumnWinterVaporConcentration = 310f,
                            ClimateZone = 3,
                            MaxVaporConcentration = 701.8f,
                            OilProduct = 1,
                            ReservoirType = 1,
                            SpringSummerVaporConcentration = 375.1f
                        },
                        new
                        {
                            Id = 8,
                            AutumnWinterVaporConcentration = 1.19f,
                            ClimateZone = 3,
                            MaxVaporConcentration = 2.25f,
                            OilProduct = 2,
                            ReservoirType = 1,
                            SpringSummerVaporConcentration = 1.6f
                        },
                        new
                        {
                            Id = 9,
                            AutumnWinterVaporConcentration = 0.15f,
                            ClimateZone = 3,
                            MaxVaporConcentration = 0.24f,
                            OilProduct = 3,
                            ReservoirType = 1,
                            SpringSummerVaporConcentration = 0.15f
                        },
                        new
                        {
                            Id = 10,
                            AutumnWinterVaporConcentration = 172.2f,
                            ClimateZone = 1,
                            MaxVaporConcentration = 384f,
                            OilProduct = 1,
                            ReservoirType = 2,
                            SpringSummerVaporConcentration = 255f
                        },
                        new
                        {
                            Id = 11,
                            AutumnWinterVaporConcentration = 0.66f,
                            ClimateZone = 1,
                            MaxVaporConcentration = 1.24f,
                            OilProduct = 2,
                            ReservoirType = 2,
                            SpringSummerVaporConcentration = 0.88f
                        },
                        new
                        {
                            Id = 12,
                            AutumnWinterVaporConcentration = 0.08f,
                            ClimateZone = 1,
                            MaxVaporConcentration = 0.13f,
                            OilProduct = 3,
                            ReservoirType = 2,
                            SpringSummerVaporConcentration = 0.08f
                        },
                        new
                        {
                            Id = 13,
                            AutumnWinterVaporConcentration = 210.2f,
                            ClimateZone = 2,
                            MaxVaporConcentration = 480f,
                            OilProduct = 1,
                            ReservoirType = 2,
                            SpringSummerVaporConcentration = 255f
                        },
                        new
                        {
                            Id = 14,
                            AutumnWinterVaporConcentration = 0.8f,
                            ClimateZone = 2,
                            MaxVaporConcentration = 1.55f,
                            OilProduct = 2,
                            ReservoirType = 2,
                            SpringSummerVaporConcentration = 1.1f
                        },
                        new
                        {
                            Id = 15,
                            AutumnWinterVaporConcentration = 0.1f,
                            ClimateZone = 2,
                            MaxVaporConcentration = 0.16f,
                            OilProduct = 3,
                            ReservoirType = 2,
                            SpringSummerVaporConcentration = 0.1f
                        },
                        new
                        {
                            Id = 16,
                            AutumnWinterVaporConcentration = 260.4f,
                            ClimateZone = 3,
                            MaxVaporConcentration = 508f,
                            OilProduct = 1,
                            ReservoirType = 2,
                            SpringSummerVaporConcentration = 308.5f
                        },
                        new
                        {
                            Id = 17,
                            AutumnWinterVaporConcentration = 0.99f,
                            ClimateZone = 3,
                            MaxVaporConcentration = 1.88f,
                            OilProduct = 2,
                            ReservoirType = 2,
                            SpringSummerVaporConcentration = 1.33f
                        },
                        new
                        {
                            Id = 18,
                            AutumnWinterVaporConcentration = 0.12f,
                            ClimateZone = 3,
                            MaxVaporConcentration = 0.19f,
                            OilProduct = 3,
                            ReservoirType = 2,
                            SpringSummerVaporConcentration = 0.12f
                        });
                });

            modelBuilder.Entity("EcoPulseBackend.Models.VehicleFlowEmissionSource.VehicleFlowEmissionSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("AverageSpeed")
                        .HasColumnType("real");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<float>("MaxTrafficIntensity")
                        .HasColumnType("real");

                    b.Property<LineString>("Points")
                        .IsRequired()
                        .HasColumnType("geometry(LineString, 4326)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Points");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Points"), "GIST");

                    b.ToTable("VehicleFlowEmissionSources");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.VehicleSpecificEmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Pollutant")
                        .HasColumnType("integer");

                    b.Property<float>("SpecificEmission")
                        .HasColumnType("real");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("VehicleSpecificEmissions");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.Weather.Weather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.Property<int>("WindDirection")
                        .HasColumnType("integer");

                    b.Property<float>("WindSpeed")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Weathers");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.Enterprise.Enterprise", b =>
                {
                    b.HasOne("EcoPulseBackend.Models.City.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.SingleEmissionSource.SingleEmissionSource", b =>
                {
                    b.HasOne("EcoPulseBackend.Models.City.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoPulseBackend.Models.Enterprise.Enterprise", "Enterprise")
                        .WithMany("SingleEmissionSources")
                        .HasForeignKey("EnterpriseId");

                    b.Navigation("City");

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.TrafficLightQueue.VehicleGroupQueue", b =>
                {
                    b.HasOne("EcoPulseBackend.Models.TrafficLightQueueEmissionSource.TrafficLightQueueEmissionSource", null)
                        .WithMany("VehicleGroups")
                        .HasForeignKey("TrafficLightQueueEmissionSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoPulseBackend.Models.TrafficLightQueueEmissionSource.TrafficLightQueueEmissionSource", b =>
                {
                    b.HasOne("EcoPulseBackend.Models.City.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.VehicleFlowEmissionSource.VehicleFlowEmissionSource", b =>
                {
                    b.HasOne("EcoPulseBackend.Models.City.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.Enterprise.Enterprise", b =>
                {
                    b.Navigation("SingleEmissionSources");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.TrafficLightQueueEmissionSource.TrafficLightQueueEmissionSource", b =>
                {
                    b.Navigation("VehicleGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
