// <auto-generated />
using System;
using EcoPulseBackend.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoPulseBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoPulseBackend.Models.PollutantInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<float?>("DailyAverageConcentration")
                        .HasColumnType("real");

                    b.Property<float?>("Mass")
                        .HasColumnType("real");

                    b.Property<float?>("MaxPermissibleConcentration")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Pollutant")
                        .HasColumnType("integer");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float?>("SpecificEmission")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PollutantInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 2,
                            Mass = 15.72f,
                            MaxPermissibleConcentration = 0.5f,
                            Name = "Твердые частицы",
                            Pollutant = 2,
                            ShortName = "PM2.5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
